/// Flutter icons Bybrisk
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bybrisk
///      fonts:
///       - asset: fonts/Bybrisk.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bybrisk {
  Bybrisk._();

  static const _kFontFam = 'Bybrisk';
  static const _kFontPkg = null;

  static const IconData deliver = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipment = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
